### ISSUE TITLE
Sveltekit - Uncaught (in promise) SyntaxError: indirect export not found: Lexer

### ISSUE THREAD

**Issue by magick93** [pablo-abc/svelte-markdown#23] opened 2021-08-27 01:47 UTC
Hello

Im getting the following error in Sveltekit:

```
Uncaught (in promise) SyntaxError: indirect export not found: Lexer
```

Am using version 0.1.10

**Comment by pablo-abc** [comment] 2021-08-29 22:28
Hey, @magick93

I'm trying to reproduce your issue with `adapter-node` but I can't seem to be able to make the error appear. I noticed the template you're using uses a quite dated version of SvelteKit (next.115), have you tried upgrading your version? Might be an issue with that.

**Comment by magick93** [comment] 2021-08-29 22:32
> I noticed the template you're using uses a quite dated version of SvelteKit (next.115), have you tried upgrading your version? 

Ah, thanks. I didnt notice that. 

Ok, will try upgrading.

**Comment by pablo-abc** [comment] 2021-12-17 02:04
I'm closing this since it's been a while without development. And we're using marked@4 now, so this _shouldn't_ be an issue anymore.

**Closed** 2021-12-17 02:04 UTC
Labels: bug
